Issue #221: Updated Dependencies and Test
- ember-cli-babel updated from ^5.1.6 to ^6.11.0 to remove deprecation warning
- ember-runtime-enumerable-includes-polyfill update from ^1.0.1 to ^2.1.0 to remove depraecation warning
- ember-cli-htmlbars-inline-precompile updated from ^0.3.1 to ^0.4.0 due to updating to ember-cli-babel@6 as per error running tests
- tests/integration/adapters/ls-adapter-test.js updated to pass 5 instead of 05 to new Date() as per build failure after updates:
SyntaxError: dummy/tests/integration/adapters/ls-adapter-test.js: Invalid number (350:30)
  348 |   const done = assert.async();
  349 | 
> 350 |   const date = new Date(1982, 05, 18);
      |                               ^
  351 |   const person = run(store, 'createRecord', 'person', {
  352 |     name: 'Dan', birthdate: date
  353 |   });